### ISSUE TITLE
REDUCE_BLOCK Effect

### ISSUE THREAD

**Issue by Xendran** [ScoreWin/letsgoraiding#38]
Due to the higher values on Block compared to other status effects, a REDUCE_BLOCK effect could prove useful to provide more control than only being able to remove all of it.

**Comment by stephencorwin** [comment]
That's a good idea. I could see that working particularly well on certain abilities.
Particularly an ability like this:
![image](https://user-images.githubusercontent.com/3931162/56106758-aabae000-5f10-11e9-9a0e-64335cf0e6f6.png)

**Comment by stephencorwin** [comment]
although a better name is probably **Inflame** 🤷‍♂️

**Comment by stephencorwin** [comment]
determined to be too specific of a keyword hate. It will be better to use REMOVE_BLOCK instead of REDUCE_BLOCK in those situations. This is partially because BLOCK is specific to Guardian abilities and only a select few neutral abilities.
