### ISSUE TITLE
Thorns does not work

### ISSUE THREAD

**Issue by Xendran** [ScoreWin/letsgoraiding#51]

**Comment by Xendran** [comment]
Upon using AoE damage skills on the mystic against two characters with Thorns, the Mystic did not recieve any thorns damage.

**Comment by stephencorwin** [comment]
This is intended. We talked about it when making this ticket #34
Thorns should not affect spells
Closed by stephencorwin 4 days ago
bug

**Comment by stephencorwin** [comment]
The decision was made to revert this change and allow thorns to affect all damage abilities.
