### ISSUE TITLE
New Ability Effects

### ISSUE THREAD

**Issue by Xendran** [ScoreWin/letsgoraiding#55]
We currently have DISCARD_ALL which gets rid of the entire hand. I'd like to see some more options here:

DISCARD_ATTACKS
DISCARD_SKILLS
DISCARD_SPELLS
DISCARD_ENCHANTMENTS
DISCARD_AGGRESSIVE
DISCARD_DEFENSIVE

----------

Although, as I look at this, this is also a set of specifications that would also be nice to apply to Cooldown Reduction. Perhaps we should investigate adding a specifier system onto effects where we can do things like this:

DISCARD_ALL
Payload: (specifier) ATTACKS

Text: Discard all attacks.

COOLDOWN_TICK
Payload: (specifier) AGGRESSIVE
Payload: (specifier) SPELLS
Payload: (value) 2

Text: Reduce cooldowns of aggressive spells by 2.

In the above example, the specifier filters in a way where both are required.
If one wanted to affect two types of cards instead, two separate effects would be scripted on the ability like so:

COOLDOWN_TICK
Payload: (specifier) SPELLS
Payload: (value) 1

COOLDOWN_TICK
Payload: (specifier) ENCHANTMENTS
Payload: (value) 1

Text: Reduce cooldowns of spells and enchantments by 1.

EDIT:

This could actually be used alongside the DRAW effect as well.

DRAW
Payload: (specifier) ENCHANTMENTS
Payload: (value) 1

Text: Draw the top enchantment of your deck.

**Comment by stephencorwin** [comment]
It definitely always be an explicit action. Payload values are meant to be generic.
I don't see ever printing a specific COOLDOWN_TICK or DISCARD for each type of ability. Cooldowns should tick down altogether. Players discard their hands at the end of turn, so this would only ever be for self-discard. I would rather have a status effect that said: "Hero can't play attacks".

Drawing the specific type of card from the top of your deck if interesting. I like the tutor parallel that it has to other card games. This features can definitely be implemented

**Comment by stephencorwin** [comment]
The effect types I am planning on adding are:
```
DRAW
DRAW_ATTACK
DRAW_SKILL
DRAW_SPELL
DRAW_ENCHANTMENT
```
