### ISSUE TITLE
Block as a hero skill

### ISSUE THREAD

**Issue by Xendran** [ScoreWin/letsgoraiding#60]
Based on how Block currently works, i'm seeing a lot of potential in granting it on a hero level.

Example: A piece of equipment with Block 2 would grant 2 Block at the start of each turn. 

This acts similar to Regenerate if you are targeted every turn, but loses value on turns where you aren't targeted. This lost value is compensated by the synergy with block skills and their ability to more reliably prevent damage-bound effects. This likely puts hero level Block on the same point value as Regenerate and Thorns.

**Comment by stephencorwin** [comment]
I don't like block acting like Regenerate and applying at the beginning of turn like this. If want to have an effect like this, we would print it as a passive select equipment.
> "At the start of turn, gain 3 Block."
